In [129]:
!pip install -U fortran-magic

In [132]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00',
                             '2017-01-07 00:00:00+00:00',
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [70]:
assert ran_the_first_cell, "Oh noes!"

In [71]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [72]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [73]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [74]:
# Lists can also be sliced, which makes a copy of elements between
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

In [75]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [76]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [77]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [78]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [79]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [80]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [81]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}

In [82]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'David': 'Hume',
 'Immanuel': 'Kant',
 'Bertrand': 'Russell',
 'Ludwig': 'Wittgenstein'}

In [83]:
del philosophers['David']
philosophers

{'Immanuel': 'Kant', 'Bertrand': 'Russell', 'Ludwig': 'Wittgenstein'}

In [84]:
# No slicing.
philosophers['Bertrand':'Immanuel']

TypeError: unhashable type: 'slice'

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [85]:
4 * "a"

'aaaa'

In [86]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [87]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]

    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [88]:
%%time

matmul(a, b)

CPU times: user 32 µs, sys: 1 µs, total: 33 µs
Wall time: 37.7 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

**My own example 0 - cpu info**

In [89]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2200.210
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi
bogomips	: 4400.42
clflush size	: 64
cache_alignment	: 64
ad

**My own example 1 - Changing in matmul(A, B) Python len(B) (# of rows of B) for len(A[0]) (# of columns of A)**

In [90]:
# cambiamos el numero de filas de b por numero de columnas de a
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]

    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(A[0])):
                out[i][j] += A[i][k] * B[k][j]
    return out

**My own example 2 - Verifiying error with in matmul(A, B) Python with the original matrices when changing len(B) (# of rows of B) for len(A[0]) (# of colums of A)**

In [91]:
# llamamos a la funcion para ver el error.
matmul(a, b)

IndexError: list index out of range

**My own example 3 - Chekcing the mtarix multiplication compatibility condition  len(A[0]) == len(B)**

In [92]:
# añadimos el condicional para ver si cumple con la condicion
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    #print(len(A[0])==len(B))
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]

    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(A[0])):
                out[i][j] += A[i][k] * B[k][j]
    return out

**My own example 4 -  Verifiying error with in matmul(A, B) Python when checking the mtarix multiplication compatibility condition  len(A[0]) == len(B)**

In [93]:
# llamamos a la funcion para verificar si numero de columnas de a == numero de filas de b
matmul(a,b)

IndexError: list index out of range

**My own example 5 - Deifining A and B that are compatible for multiplcation**

In [94]:
b = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

a = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

**My own example 6 - Runinng the correct Python matrix multiplication code with the matrices with dimensions compatible for multiplication.**

In [95]:
import random

In [96]:
random.normalvariate(0,1)

0.21244719740523976

In [97]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.5852501076264499, 0.34948720733526384, 0.5200555658510223],
 [0.9173872393456823, 0.021502437628399318, 0.24999657333722236]]

**My own example 7 - Running 10 times matmul(randa, randb) with randa and randb a randon matrices of 600 x 100 and 100 x 600 and calulating the average execution time**

In [98]:
import time


# Inicializa una lista para almacenar los tiempos de ejecución
tiempos_ejecucion = []

# Realiza la multiplicación de matrices 10 veces y mide el tiempo de ejecución
for _ in range(10):
    randa = random_matrix(600, 100)
    randb = random_matrix(100, 600)
    tiempo_inicio = time.time()
    resultado = matmul(randa, randb)
    tiempo_fin = time.time()
    tiempo_ejecucion = tiempo_fin - tiempo_inicio
    tiempos_ejecucion.append(tiempo_ejecucion)

# Calcula el tiempo de ejecución promedio
tiempo_ejecucion_promedio = sum(tiempos_ejecucion) / len(tiempos_ejecucion)

print(f"Tiempo de ejecución promedio: {tiempo_ejecucion_promedio} segundos")

Tiempo de ejecución promedio: 9.684286785125732 segundos


**My own example 8 - Creating the average execution time data frame and adding Python's average execution time**

In [99]:
dic = {'Languages':['Phyton'],'Average Secs':[ tiempo_ejecucion_promedio]}
dFrame = pd.DataFrame(dic)
print(dic)

{'Languages': ['Phyton'], 'Average Secs': [9.684286785125732]}


**My own example 9 - Running 10 times randa and randb mutiplicaction as NumPy arrays  adding NumPy's average execution time**

In [100]:
import numpy as np
import time

tiempos_ejecucion = []

# Realiza la multiplicación de matrices 10 veces y mide el tiempo de ejecución

for _ in range(10):
    randa = random_matrix(600, 100)
    randb = random_matrix(100, 600)
    tiempo_inicio = time.time()
    resultado = np.matmul(randa, randb)
    tiempo_fin = time.time()
    tiempo_ejecucion = tiempo_fin - tiempo_inicio
    tiempos_ejecucion.append(tiempo_ejecucion)

# convieerte la lista a nunpy array
execution_times_np = np.array(tiempos_ejecucion)

# promedio
average_execution_time = np.mean(execution_times_np)

print(f"Average execution time: {average_execution_time} seconds")

Average execution time: 0.017935013771057128 seconds


In [101]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 8.62 s, sys: 25.5 ms, total: 8.65 s
Wall time: 8.66 s


In [102]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [156]:
%fortran_config --clean-cache
%load_ext fortranmagic

Clean cache: /root/.cache/ipython/fortranmagic/ea3d515d
The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


In [157]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result

    result = sum(xs * ys)
end

In [158]:
import numpy as np
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [159]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [160]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 16.3 ms, sys: 964 µs, total: 17.2 ms
Wall time: 22.6 ms


333328333350000.0

In [161]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 0 ns, sys: 190 µs, total: 190 µs
Wall time: 196 µs


333328333350000.0

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


**My own example 10 - Deifining A (2x2)  and B (2x2)**

In [162]:
A = random_matrix(2, 2)
B = random_matrix(2, 2)

**My own example 11 - Defining Fortran subroutine matmul(A,B) for 2x2 matrices**

In [164]:
%%fortran --extra "-DF2PY_REPORT_ON_ARRAY_COPY=1"
subroutine fortran_matmul(A, B, n,C)
  integer, intent(in) :: n
  real(8), dimension(n,2), intent(in) :: A
  real(8), dimension(n,2), intent(in) :: B
  real(8), dimension(n,2), intent(out) :: C
  do i = 1, 2
    do j = 1, 2
      do k = 1, 2
        C(i,j) = C(i,j) + a(i,k)*b(k,j)
      end do
    end do
  end do
end subroutine fortran_matmul

**My own example 12 -Run Fortran subroutine matmul(A,B) with a and b 2x2 matrices**

In [165]:
a= np.array(A, dtype='f8', order='F')
b= np.array(B, dtype='f8', order='F')

In [166]:
%%time

fortran_matmul(a, b)

CPU times: user 24 µs, sys: 1 µs, total: 25 µs
Wall time: 30.8 µs


array([[0.65720347, 0.50068857],
       [0.64946985, 0.5145937 ]])

In [148]:
print(a)
print(b)

[[0.89577537 0.92697767 0.99819724 ... 0.44624042 0.10868487 0.50007451]
 [0.37942461 0.83717689 0.98845937 ... 0.52864873 0.29496354 0.95467626]
 [0.66532068 0.59222393 0.42824434 ... 0.50664713 0.35655531 0.60133024]
 ...
 [0.53045887 0.41793669 0.76357094 ... 0.28458389 0.92612413 0.2050619 ]
 [0.38940788 0.20176989 0.71410291 ... 0.21436794 0.56510762 0.76565454]
 [0.49951623 0.87214573 0.07408424 ... 0.50164176 0.03292403 0.93172411]]
[[0.08709861 0.95472372 0.21307925 ... 0.54842098 0.30041344 0.83383459]
 [0.40344074 0.9129198  0.76284334 ... 0.30852329 0.56880824 0.61879372]
 [0.49108725 0.60511963 0.24035634 ... 0.91016308 0.61843889 0.38069289]
 ...
 [0.022901   0.26593138 0.78598867 ... 0.60199904 0.59632896 0.11290006]
 [0.18552143 0.02877588 0.16155374 ... 0.24221384 0.96212469 0.72915895]
 [0.54548761 0.23926789 0.95661663 ... 0.15419551 0.91412247 0.12512352]]


**My own example 13 - Defining Fortran subroutine matmul(A,B) for 600x100 and 100x600 matrices**

In [167]:
%%fortran --extra "-DF2PY_REPORT_ON_ARRAY_COPY=1"
subroutine fortran_matmul(A, B,C)
  real(8), dimension(600,100), intent(in) :: A
  real(8), dimension(100,600), intent(in) :: B
  real(8), dimension(600,600), intent(out) :: C
  do i = 1, 600
    do j = 1, 600
      do k = 1, 100
        C(i,j) = C(i,j) + a(i,k)*b(k,j)
      end do
    end do
  end do
end subroutine fortran_matmul

**My own example 14 -Run Fortran subroutine matmul(A,B) with 600x100 and 100x600 matrices**

In [168]:
%%time
A = random_matrix(600, 100)
B = random_matrix(100, 600)
a= np.array(A, dtype='f8', order='F')
b= np.array(B, dtype='f8', order='F')
fortran_matmul(a, b)

CPU times: user 76.9 ms, sys: 0 ns, total: 76.9 ms
Wall time: 77.7 ms


array([[27.03495911, 26.80828855, 25.11230701, ..., 25.41501254,
        25.66831169, 21.97534265],
       [26.9401639 , 24.36182824, 20.74063508, ..., 24.7042251 ,
        25.21855745, 22.66748523],
       [24.66115811, 23.3649405 , 22.37798952, ..., 22.5084168 ,
        25.82137667, 23.77954399],
       ...,
       [24.88223874, 25.98167342, 23.57307181, ..., 25.01937787,
        24.24603434, 25.13951466],
       [26.01796854, 27.64882927, 24.72868109, ..., 25.45185078,
        25.91741075, 23.38501556],
       [23.65846546, 23.63001395, 23.0595744 , ..., 22.52232187,
        23.64220265, 22.36089827]])

**My own example 15 - Running 10 times the  Fortran subroutine matmul(A,B) with 600x100 and 100x600 matrices and adding Fortran magic average execution time to the data frame**

In [169]:
import numpy as np
import time

# Realiza la multiplicación de matrices 10 veces y mide el tiempo de ejecución
tiempos_ejecucion = []
for _ in range(10):
    randa = random_matrix(600, 100)
    randb = random_matrix(100, 600)
    a= np.array(randa, dtype='f8', order='F')
    b= np.array(randb , dtype='f8', order='F')
    tiempo_inicio = time.time()
    resultado = fortran_matmul(a, b)
    tiempo_fin = time.time()
    tiempo_ejecucion = tiempo_fin - tiempo_inicio
    tiempos_ejecucion.append(tiempo_ejecucion)

# convieerte la lista a nunpy array
execution_times_np = np.array(tiempos_ejecucion)

# promedio
average_execution_time = np.mean(execution_times_np)

print(f"Average execution time: {average_execution_time} seconds")

Average execution time: 0.06127808094024658 seconds


**My own example 16 - Creating a  Fortran program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [170]:
%%writefile tmpff.f
      Subroutine matmulti()
        INTEGER, DIMENSION(100,600) :: A
        INTEGER, DIMENSION(600,100) :: B
        INTEGER, DIMENSION(600,600) :: C
        INTEGER :: x, j
        A(1,1) = 2
        B(1,1) = 2
        C = matmul(B,A)
      END

      program TEST
        integer :: i
        real*8 :: prom
        real*8 :: start_time, end_time, total_time


        DO i=0,9
          call cpu_time(start_time) ! registrar el tiempo de inicio de la multiplicación
          call matmulti()
          call cpu_time(end_time) ! registrar el tiempo de fin de la multiplicación
          total_time = end_time - start_time ! calcular el tiempo total de la multiplicación
          prom = prom + total_time
        END DO
        prom = prom / 10
        write(*,*) "prom: ", prom
        stop
      end

Writing tmpff.f


**My own example 17 - Running the Fortran program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [171]:
%%time
!gfortran tmpff.f -o tmpff
!./tmpff

 prom:    6.9389000000000022E-003
CPU times: user 11.6 ms, sys: 3.08 ms, total: 14.7 ms
Wall time: 519 ms


**My own example 18 - Adding Fortran average execution time to the data frame**

In [172]:
nuevo_elemento = pd.DataFrame({'Languages': 'Fortran', 'Average Secs':6.6792000000000015E-003}, index=[1])

dFrame = pd.concat([dFrame, nuevo_elemento])

dFrame

Languages  Average Secs
0    Phyton      9.684287
1   Fortran      0.006679

**My own example 19 - Creating a c program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [173]:
%%writefile tmpc.c
#define N 600
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
void crear_matriz(int A[N][N], int filas, int columnas);
void escribir_matriz(int A[N][N], int filas, int columnas);
void multiplicar(int A[N][N], int B[N][N],int C[N][N]);
void test();
void  test()
{
 int m, n, p;
 int A[N][N], B[N][N], C[N][N];
 m = 600;
 n = 100;
 crear_matriz(A, m, n);
 p = 600;
 crear_matriz(B, n, p);
 multiplicar(A, B, C);
 return;
}
void crear_matriz(int A[N][N], int filas, int columnas)
{
 int i, j;
 for (i=0; i<filas; i++)
 {
  for (j=0; j<columnas; j++)
  {
   A[i][j] = rand() % 100;
  }
 }
 return;
}
void escribir_matriz(int A[N][N], int filas, int columnas)
{
 for (int i=0; i<600; i++)
 {
  for (int j=0; j<600; j++)
  {
   printf("\t%d", A[i][j]);
  }
  printf("\n");
 }
 return;
}
void multiplicar(int A[N][N], int B[N][N], int C[N][N])
{
 int i, j, k;
 for(i=0; i<600; i++)
  for(k=0; k<600; k++)
   C[i][k]=0;

 for (i=0; i<600; i++)
  for (j=0; j<600; j++)
   for (k=0; k<100; k++)
    C[i][k] = C[i][k] + A[i][j]*B[j][k];
}
int main(){
    double time_spent = 0.0;
    double times[10];

    int i;
    for(i=0;i<10;i++){
        clock_t begin = clock();
        test();
        clock_t end = clock();
        time_spent += (double)(end - begin) / CLOCKS_PER_SEC;
        times[i] = time_spent;
    }

    double prom = 0;
    for(i=0;i<10;i++){
        prom += times[i];
    }
    prom = prom/10;
    printf("\t%f",prom);
}

Writing tmpc.c


**My own example 20 - Running the c program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [174]:
!gcc tmpc.c -o tmpc
!./tmpc

	0.992612

**My own example 21 - Adding c average execution time to the data frame**

In [175]:
nuevo_elemento = pd.DataFrame({'Languages': 'C', 'Average Secs': 1.509242}, index=[2])

dFrame = pd.concat([dFrame, nuevo_elemento])

dFrame

Languages  Average Secs
0    Phyton      9.684287
1   Fortran      0.006679
2         C      1.509242

**My own example 22 - Creating a C++ program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [176]:
%%writefile tmpcc.cc
#include <iostream>
#include <chrono>

using namespace std;
using namespace chrono;

void test();

void test()
{
    int matriz1[600][100];
    int matriz2[100][600];
    int result[600][600];

    // Generar valores aleatorios para las matrices
    for(int i = 0; i < 600; i++) {
        for(int j = 0; j < 100; j++) {
            matriz1[i][j] = rand() % 100;
        }
    }

    for(int i = 0; i < 100; i++) {
        for(int j = 0; j < 600; j++) {
            matriz2[i][j] = rand() % 100;
        }
    }

    for (int i = 0; i < 600; i++) {
        for (int j = 0; j < 600; j++) {
            result[i][j] = 0;
            for (int k = 0; k < 100; k++) {
                result[i][j] += matriz1[i][k] * matriz2[k][j];
            }
        }
    }

    return;
}
int main(){
    float tiempos[10];

    for(int i=0; i<10; i++){
        auto start = high_resolution_clock::now();

        test();

        // Crear un punto de finalización para medir el tiempo
        auto stop = high_resolution_clock::now();

        // Calcular la duración en segundos como un valor double
        auto duration = duration_cast<microseconds>(stop - start);
        tiempos[i] = duration.count();
    }

    float prom=0;
    for(int i=0; i<10; i++){
        prom += tiempos[i];
    }
    cout << prom/10 << endl;
}

Writing tmpcc.cc


**My own example 23 - Running the C++ program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [177]:
!g++ tmpcc.cc -o tmpcc
!./tmpcc

176534


**My own example 24 - Adding C++ average execution time to the data frame**

In [178]:
nuevo_elemento = pd.DataFrame({'Languages': 'C++', 'Average Secs': 0.167304}, index=[3])

dFrame = pd.concat([dFrame, nuevo_elemento])

dFrame

Languages  Average Secs
0    Phyton      9.684287
1   Fortran      0.006679
2         C      1.509242
3       C++      0.167304

**My own example 25 - Creating a Java program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [179]:
%%writefile Main.java
 class Main {
    public static void main(String[] args) {
        long[] tiempos = new long[10];

        for(int i=0;i<10;i++){
            long startTime = System.nanoTime();
            test();
            long endTime = System.nanoTime();

            long duration = (endTime - startTime) / 1000000;

            tiempos[i] = duration;
        }

        long prom = 0;
        for(int i=0;i<10;i++){
            prom += tiempos[i];
        }
        prom = prom/10;
        System.out.println(prom + " nanosegundos");
    }

    public static void test(){
        final int ROWS1 = 600; // Definir el número de filas de la primera matriz
        final int COLS1 = 100; // Definir el número de columnas de la primera matriz
        final int ROWS2 = 100; // Definir el número de filas de la segunda matriz
        final int COLS2 = 600; // Definir el número de columnas de la segunda matriz

        // Definir las dos matrices a multiplicar
        int[][] mat1 = new int[ROWS1][COLS1];
        int[][] mat2 = new int[ROWS2][COLS2];

        // Llenar las matrices con valores aleatorios
        for (int i = 0; i < ROWS1; i++) {
            for (int j = 0; j < COLS1; j++) {
                mat1[i][j] = (int) (Math.random() * 10);
            }
        }
        for (int i = 0; i < ROWS2; i++) {
            for (int j = 0; j < COLS2; j++) {
                mat2[i][j] = (int) (Math.random() * 10);
            }
        }

        // Definir la matriz donde se almacenará el resultado de la multiplicación
        int[][] result = new int[ROWS1][COLS2];

        // Multiplicar las dos matrices y almacenar el resultado en la matriz result
        for (int i = 0; i < ROWS1; i++) {
            for (int j = 0; j < COLS2; j++) {
                result[i][j] = 0;
                for (int k = 0; k < ROWS2; k++) {
                    result[i][j] += mat1[i][k] * mat2[k][j];
                }
            }
        }
    }
}

Writing Main.java


**My own example 26 - Running the Java program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [180]:
!javac Main.java
!java Main

104 nanosegundos


**My own example 27 - Adding Java average execution time to the data frame**

In [181]:
nuevo_elemento = pd.DataFrame({'Languages': 'Java', 'Average Secs': 0.000000090}, index=[4])

dFrame = pd.concat([dFrame, nuevo_elemento])

dFrame

Languages  Average Secs
0    Phyton  9.684287e+00
1   Fortran  6.679200e-03
2         C  1.509242e+00
3       C++  1.673040e-01
4      Java  9.000000e-08

**My own example 28 - Creating a Javascript program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [182]:
%%writefile tmp.js
function multiplicarMatrices(matrizA, matrizB) {
  const filasA = 600;
  const columnasA = 100;
  const filasB = 100;
  const columnasB = 600;

  // Inicializar matriz de resultado
  const matrizC = new Array(filasA);
  for (let i = 0; i < filasA; i++) {
    matrizC[i] = new Array(columnasB).fill(0);
  }

  // Multiplicar matrices
  for (let i = 0; i < filasA; i++) {
    for (let j = 0; j < columnasB; j++) {
      for (let k = 0; k < columnasA; k++) {
        matrizC[i][j] += matrizA[i][k] * matrizB[k][j];
      }
    }
  }

  // Retornar matriz de resultado
  return matrizC;
}

// Crear matrices de ejemplo
const matrizA = new Array(600);
for (let i = 0; i < 600; i++) {
  matrizA[i] = new Array(100);
  for (let j = 0; j < 100; j++) {
    matrizA[i][j] = 1;
  }
}
const matrizB = new Array(100);
for (let i = 0; i < 100; i++) {
  matrizB[i] = new Array(600);
  for (let j = 0; j < 600; j++) {
    matrizB[i][j] = 2;
  }
}

// Multiplicar matrices 10 veces y calcular tiempo de ejecución
let total = 0;
for (let i = 0; i < 10; i++) {
    const startTime = new Date().getTime();
    const matrizC = multiplicarMatrices(matrizA, matrizB);
    const endTime = new Date().getTime();
    const duration = endTime - startTime;
    total += duration;
}

const prom = total/10;
console.log(prom);

Writing tmp.js


**My own example 29 - Running the Javascript program that mutiplies 10 times A(600x100) and  B (100x600) matrices**

In [183]:
!node tmp.js

313.5


**My own example 30 - Adding Javascript average execution time to the data frame**

In [184]:
nuevo_elemento = pd.DataFrame({'Languages': 'JavaScript', 'Average Secs': 0.3461}, index=[5])

dFrame = pd.concat([dFrame, nuevo_elemento])

dFrame

Languages  Average Secs
0      Phyton  9.684287e+00
1     Fortran  6.679200e-03
2           C  1.509242e+00
3         C++  1.673040e-01
4        Java  9.000000e-08
5  JavaScript  3.461000e-01

**My own example 31 - Finding the minimun average esecuiton time in the data frame**

In [185]:
min_time = dFrame['Average Secs'].min()
tiempo_minimo = dFrame.loc[dFrame['Average Secs'] == min_time]
tiempo_minimo

Languages  Average Secs
4      Java  9.000000e-08

**My own example 32 - Adding the Speed factor columne to the data frame**

In [186]:
dFrame = dFrame.assign(Speed_Factor=[dFrame.loc[dFrame['Languages'] == 'Java', 'Average Secs'].iloc[0] /dFrame.loc[dFrame['Languages'] == 'Phyton', 'Average Secs'].iloc[0],
                             dFrame.loc[dFrame['Languages'] == 'Java', 'Average Secs'].iloc[0] / dFrame.loc[dFrame['Languages'] == 'Fortran', 'Average Secs'].iloc[0],
                             dFrame.loc[dFrame['Languages'] == 'Java', 'Average Secs'].iloc[0] / dFrame.loc[dFrame['Languages'] == 'C', 'Average Secs'].iloc[0],
                             dFrame.loc[dFrame['Languages'] == 'Java', 'Average Secs'].iloc[0] / dFrame.loc[dFrame['Languages'] == 'C++', 'Average Secs'].iloc[0],
                             dFrame.loc[dFrame['Languages'] == 'Java', 'Average Secs'].iloc[0] / dFrame.loc[dFrame['Languages'] == 'Java', 'Average Secs'].iloc[0],
                             dFrame.loc[dFrame['Languages'] == 'Java', 'Average Secs'].iloc[0] / dFrame.loc[dFrame['Languages'] == 'JavaScript', 'Average Secs'].iloc[0]])
print(dFrame)

    Languages  Average Secs  Speed_Factor
0      Phyton  9.684287e+00  9.293405e-09
1     Fortran  6.679200e-03  1.347467e-05
2           C  1.509242e+00  5.963258e-08
3         C++  1.673040e-01  5.379429e-07
4        Java  9.000000e-08  1.000000e+00
5  JavaScript  3.461000e-01  2.600405e-07


**My own example 33 - Sorting the the data frame by average execution time**

In [187]:
dFrame = dFrame.sort_values('Average Secs')
dFrame

Languages  Average Secs  Speed_Factor
4        Java  9.000000e-08  1.000000e+00
1     Fortran  6.679200e-03  1.347467e-05
3         C++  1.673040e-01  5.379429e-07
5  JavaScript  3.461000e-01  2.600405e-07
2           C  1.509242e+00  5.963258e-08
0      Phyton  9.684287e+00  9.293405e-09

## Why is the Python Version so Much Slower?

In [ ]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

In [ ]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

In [ ]:
data + data

In [ ]:
%%time
# Naive dot product
(array_data * array_data).sum()

In [ ]:
%%time
# Built-in dot product.
array_data.dot(array_data)

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

In [ ]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

In [ ]:
# We also can't grow an array once it's created.
data.append(3)

In [ ]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [ ]:
data = np.arange(15).reshape(3, 5)
data

In [ ]:
# Binary operators.
data * data

In [ ]:
# Unary functions.
np.sqrt(data)

In [ ]:
# Comparison operations
(data % 3) == 0

In [ ]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

In [ ]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [ ]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

In [ ]:
# Slicing works with the same semantics as Python lists.
sines[0]

In [ ]:
sines[:3]  # First three elements

In [ ]:
sines[5:]  # Elements from 5 on.

In [ ]:
sines[::2]  # Every other element.

In [ ]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

In [ ]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

In [ ]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [ ]:
sort_indices = np.argsort(unsorted_data)
sort_indices

In [ ]:
unsorted_data[sort_indices]

In [ ]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [ ]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

In [ ]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

In [ ]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

On multi-dimensional arrays, we can slice along each axis independently.

In [ ]:
data = np.arange(25).reshape(5, 5)
data

In [ ]:
data[:2, :2]  # First two rows and first two columns.

In [ ]:
data[:2, [0, -1]]  # First two rows, first and last columns.

In [ ]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [ ]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [ ]:
variance(np.random.standard_normal(1000))

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [ ]:
data = np.arange(30)
data.mean()

- ...but we can do more interesting things with multi-dimensional arrays.

In [ ]:
data = np.arange(30).reshape(3, 10)
data

In [ ]:
data.mean()

In [ ]:
data.mean(axis=0)

In [ ]:
data.mean(axis=1)

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [ ]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

In [ ]:
row + column

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [ ]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for:
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [ ]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

In [ ]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

In [ ]:
# We can look up values out of a Series by position...
s.iloc[0]

In [ ]:
# ... or by label.
s.loc['a']

In [ ]:
# Slicing works as expected...
s.iloc[:2]

In [ ]:
# ...but it works with labels too!
s.loc[:'c']

In [ ]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

In [ ]:
# As does boolean masking.
s.loc[s > 2]

In [ ]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

In [ ]:
s + other_s

In [ ]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

In [ ]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

In [ ]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

# Rolling Operations

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [ ]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [ ]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)

    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

# Thanks!